# Generated by Django 3.1.4 on 2020-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans_opt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterations',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
