# Generated by Django 3.1.4 on 2020-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans_opt', '0003_auto_20201202_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='question_answer_1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='question_answer_2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='question_answer_3',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
